### ISSUE TITLE
Change implementation from Exclude List to Include List

### ISSUE THREAD

**Issue by rexkix** [ashbash1987/ktanemod-modselector#29]
When a new module comes out, it's enabled in everybody's profile by default.  This makes it a configuration management nightmare for people with many profiles for many experts.

Please redesign *everything* so that it works based on an Include list rather than an Exclude list.

**Comment by ashbash1987** [comment]
I see that this would be a problem in the counter-example of you subscribing to a new a module, and it not being enabled in *any* of the profiles at all. So, you'd still have to manage profiles anyway just to get new things to appear. Having it the way it is currently means that it doesn't prohibit new content from coming in immediately.

I understand where you are coming from with the whole 'experting' profile issue. I don't want a heavy-handed solution that 'catches all', because I know that some people won't want it to be a catch-all.

It might be that profiles have an additional property on them that indicates how they should mutate for new content. That way, 'experting' profiles could mutate to automatically add any new things not listed, whereas other standard profiles won't mutate. Closing this issue as this idea I've spitballed is completely different to what has been asked of in the initial post.

**Comment by rexkix** [comment]
You know, the more I see the tool used in action, the more it seems that people are responsible for maintaining their own experting profile, including disabling new modules as they come out.  Of course, they never do, but when I get a new profile from somebody, I check it for new modules that are not disabled.  It is a hassle, but not a huge one, as long as it's only one profile.

I retract this suggestion.  The tool is fine as it is.  Thanks, Ash.
